# Generated by Django 4.2.1 on 2023-05-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('fact_qliq_data1', models.FloatField()),
                ('fact_qliq_data2', models.FloatField()),
                ('fact_qoil_data1', models.FloatField()),
                ('fact_qoil_data2', models.FloatField()),
                ('forecast_qliq_data1', models.FloatField()),
                ('forecast_qliq_data2', models.FloatField()),
                ('forecast_qoil_data1', models.FloatField()),
                ('forecast_qoil_data2', models.FloatField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
