# Generated by Django 4.2.1 on 2023-05-05 14:51

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
